name: MSDO Scan

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  security-events: write   # 🔥 IMPORTANT

jobs:
  security:
    runs-on: windows-latest
    continue-on-error: false

    steps:
    - uses: actions/checkout@v3
          
    - name: Run Microsoft Security DevOps
      uses: microsoft/security-devops-action@preview
      id: msdo

    - name: Upload alerts to Security tab
      uses: github/codeql-action/upload-sarif@v3   # 🔥 FIX
      with:
        sarif_file: ${{ steps.msdo.outputs.sarifFile }}
